### ISSUE TITLE
dialog not shown before navigating & after adding post in addPost.dart

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#113]
**Describe the bug**
dialog not shown before navigating & after adding post in addPost.dart

**To Reproduce**
1. Go to 'add post from the floating button'
2. fill some random things
3. Click on 'add post'
4. See error( it waits for 3 seconds and navigates to homepage the dialog is not shown)

**Expected behavior**
the dialog should be shown for 3 secs and then navigate to home page

**Comment by navinkumar-k-015** [comment]
I solved this issue but I need to check pls can you unblock me firestore.

**Comment by navinkumar-k-015** [comment]
![Screenshot_1602846055](https://user-images.githubusercontent.com/61898825/96250893-319cbd00-0fcd-11eb-9251-0ae8d26b53ac.png)

**Comment by hayat-tamboli** [comment]
@navinkumar-k-015 you should have requested for assigning this issue to you, you just scared the hell out of me🤪.

**Comment by hayat-tamboli** [comment]
![image](https://user-images.githubusercontent.com/55529269/96251638-60676300-0fce-11eb-8c2a-7a951cbc0b64.png)
## just comment these lines

**Comment by hayat-tamboli** [comment]
@navinkumar-k-015 provide a screen recording of adding an event and opening dialog and then a waiting for 3 seconds and then automatically navigating to home page

**Comment by navinkumar-k-015** [comment]
![test1](https://user-images.githubusercontent.com/61898825/96254704-5bf17900-0fd3-11eb-80fe-ff25cb7bfb34.gif)
Here is the recording

**Comment by navinkumar-k-015** [comment]
> # @navinkumar-k-015 you should have requested for assigning this issue to you, you just scared the hell out of me🤪.

Yeah sorry for causing trouble.
I recommend adding validator to form as I was not selecting the purpose which causes the problem

**Comment by navinkumar-k-015** [comment]
I am creating a pull request so If it's correct pls merge it.

**Comment by hayat-tamboli** [comment]
> > # @navinkumar-k-015 you should have requested for assigning this issue to you, you just scared the hell out of me🤪.
> 
> Yeah sorry for causing trouble.
> I recommend adding validator to form as I was not selecting the purpose which causes the problem

great suggestion I will look onto it
