### ISSUE TITLE
add funtionality for adding and decline a friend request from notification

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#118]
![image](https://user-images.githubusercontent.com/55529269/96337699-84967300-10a6-11eb-9723-e2132f20024c.png)

![image](https://user-images.githubusercontent.com/55529269/96337727-a7c12280-10a6-11eb-89ef-40d53eb2db21.png)

**Comment by bigblackclock** [comment]
I could add it

**Comment by hayat-tamboli** [comment]
> I could add it

@bigblackclock we have almost solved this issue, so sorry, but keep up the spirit and keep contributing to open source ✌🏼
