### ISSUE TITLE
fix search bar/appbar color in dark friend list 

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#124]
**Describe the bug**
weird colors pop up when searching for users in friends list in profile page

**To Reproduce**
1. Go to profile page
2. Click on 'friends'
3. click the search bar

**Expected behavior**
the app bar color should be somewhat black

**Screenshots**
![image](https://user-images.githubusercontent.com/55529269/96367457-8d04b180-116b-11eb-984f-0593e769612a.png)

**Comment by krish-bhanushali** [comment]
did you find solution to this?

**Comment by hayat-tamboli** [comment]
Not yet @krish-bhanushali , if you want you can try to fix

**Comment by krish-bhanushali** [comment]
Yes sure
