### ISSUE TITLE
chat not working properly

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#125]
**Describe the bug**
list dynamic not a subtype of list string

**To Reproduce**
1. Go to 'message page'
2. Click on 'any chat'
3. See error

**Expected behavior**
chat screen shot pop up with that person

**Screenshots**
![error in chats](https://user-images.githubusercontent.com/55529269/96368454-80835780-1171-11eb-9eb9-f390087f7bdb.gif)

**Comment by sbangariGIT** [comment]
Sent PR for this
