### ISSUE TITLE
Add A list of all pages in readme.md

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#14]
* Add all page name in readme.md
* add it after [author](https://github.com/Runbhumi/Runbhumi#author) & before [contributing](https://github.com/Runbhumi/Runbhumi#-contributing)

**Comment by Arsenic-ATG** [comment]
I am interested in doing this task. 🙂

but I have a doubt :- 
Q. what do you mean by ```list of pages```  here ?

**Comment by hayat-tamboli** [comment]
Our App has different pages/screens such as 
* splash screen
* login page
* signup page
* forgot password page
* home page
:
:
* etc
which @sbangariGIT and @mohitreddy03  knows more about,
so I wanted to list out all the pages/screens so that our team would know where we stand in our project

**Comment by Arsenic-ATG** [comment]
Oh I missed the part in your [Readme.md](https://github.com/Runbhumi/Runbhumi/blob/master/README.md) which says

> Contributions are only made by organisation members

I thought it was open for everyone for contribute
sorry for bothering you and your team 🙂

**Comment by hayat-tamboli** [comment]
Actually this project is for our college but this repo will be open for all to contribute after October(when we submit version 1.0+)
some small contributions in readme will still be accepted 👍🏼
