### ISSUE TITLE
Add a limit to the number of people registering for a event

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#141]
**Is your feature request related to a problem? Please describe.**
any number of users can attend an event which should not happen

**Describe the solution you'd like**
add a field to take input from a user of the max number of users and show it in the event in the feed/home page and then make the event disappear if the event reached its 100% limit.

- [x]  make design

- [x] make the frontend part of it

- [x] integrate backend logic

**Describe alternatives you've considered**
alternatively, I thought of making a default limit like cricket having a limit of 22, football 22, basketball 10 etc

**Comment by Manas1820** [comment]
@hayat-tamboli Pls provide me an overview of the UI how you are planning to complete this!

**Comment by hayat-tamboli** [comment]
> @hayat-tamboli Pls provide me an overview of the UI how you are planning to complete this!

![image](https://user-images.githubusercontent.com/55529269/99078721-dae2cd00-25e4-11eb-9fc5-e6e6ae9f1c20.png)
![image](https://user-images.githubusercontent.com/55529269/99078756-e930e900-25e4-11eb-97ac-b8d03c087f6d.png)
