### ISSUE TITLE
Add an OPT OUT button in schedule part

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#142]
**Is your feature request related to a problem? Please describe.**
A user cant opt-out of an event

**Describe the solution you'd like**
<img width="680" alt="Profile-schedule page - presentation" src="https://user-images.githubusercontent.com/55529269/97533588-79184580-19de-11eb-8795-7ab2269d7604.png">

- [x] add a front end button

- [x] add the backend logic

**Comment by Manas1820** [comment]
@hayat-tamboli is this complete?
