### ISSUE TITLE
Reaction to text message 

### ISSUE THREAD

**Issue by Manas1820** [Runbhumi/Runbhumi#147]
**Is your feature request related to a problem? Please describe.**
Reactions to a text message in the chatbox can be added.

**Describe the solution you'd like**
just have a different collection for that message since every message is having a unique id. 

**Additional context**
![image](https://user-images.githubusercontent.com/53006261/97786790-feb11680-1bd3-11eb-964c-3bbdf7ac9ea3.png)
 It can look somewhat like this but just some sports-related emoticons

**Comment by hayat-tamboli** [comment]
OUT of MVP
