### ISSUE TITLE
Need a Success Profile Update Notification 

### ISSUE THREAD

**Issue by Manas1820** [Runbhumi/Runbhumi#162]
**Is your feature request related to a problem? Please describe.**
It's for the user to know that they have successfully updated their profile

**Describe the solution you'd like**
A simple illustration can be used.

**Comment by hayat-tamboli** [comment]
@Manas1820 in #188 I have added a functionality to navigate to previous page when clicking save profile. Does this solve your problem.

**Comment by Manas1820** [comment]
@hayat-tamboli yes this solves

**Comment by hayat-tamboli** [comment]
> @hayat-tamboli yes this solves. by the way, you are navigating him back to the profile page right?

Actually it navigates back to drawer open page
