### ISSUE TITLE
filter events by sports🎾🏈🏒🏓🏐

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#163]
**Is your feature request related to a problem? Please describe.**
whenever a user wants to search for events of a specific sport  there is no such feature like that

**Describe the solution you'd like**
the user should be able to do that by clicking any sport from the category which opens a new page with events from only that sports 

![image](https://user-images.githubusercontent.com/55529269/98638026-50357000-234f-11eb-9d66-28251a22f74e.png)
![image](https://user-images.githubusercontent.com/55529269/98638045-59264180-234f-11eb-8487-e1a63d0c6c9b.png)

**Comment by Manas1820** [comment]
@hayat-tamboli  will need a final touch of UI and dates are missing in the second screen
