### ISSUE TITLE
paid / unpaid options in events

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#303]
**Is your feature request related to a problem? Please describe.**
A clear and concise seperation of paid and unpaid events

**Describe the solution you'd like**
something similar to public/private sepration

- [x] backend work

- [x] frontend work

**Comment by sbangariGIT** [comment]
@hayat-tamboli are you adding the frontend part of it or do you want me to make the basic UI which you can edit later

**Comment by hayat-tamboli** [comment]
U will only be adding the frontend work in the event card to show them whether they r paid or not

**Comment by hayat-tamboli** [comment]
> @hayat-tamboli are you adding the frontend part of it or do you want me to make the basic UI which you can edit later

Yaa u make the basic ui I will edit that later

**Comment by sbangariGIT** [comment]
But we need something on the add post page as well

**Comment by hayat-tamboli** [comment]
> But we need something on the add post page as well
> 

Yaa u can use the same ui as private and public

**Comment by sbangariGIT** [comment]
Finished the backend plus the add post UI. @Manas1820 can you review the backend just to be sure. Only thing left is the UI for the explore events card

**Comment by hayat-tamboli** [comment]
Yup I will do the frntend of event card
