### ISSUE TITLE
Please report All your renderflex issues/ pixel overflow here

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#304]
**Describe the bug**
the black yellow strip things which comes due to render flex issues
@sbangariGIT @Manas1820 @mohitreddy03

**Comment by Manas1820** [comment]
![image](https://user-images.githubusercontent.com/53006261/106814889-15ff1480-6699-11eb-8835-2a72eb1a68a0.png)

**Comment by hayat-tamboli** [comment]
![image](https://user-images.githubusercontent.com/55529269/107355809-fed78100-6af5-11eb-8c8e-84d40f57886d.png)

**Comment by hayat-tamboli** [comment]
![image](https://user-images.githubusercontent.com/55529269/107355860-10b92400-6af6-11eb-9f7e-60aa92eb2f1f.png)

**Comment by hayat-tamboli** [comment]
![Uploading image.png…]()

**Comment by hayat-tamboli** [comment]
![image](https://user-images.githubusercontent.com/55529269/107357069-98536280-6af7-11eb-95ec-077c61a0bfa6.png)

**Comment by mohitreddy03** [comment]
![image](https://user-images.githubusercontent.com/61975605/107538840-63740800-6bea-11eb-88ce-5e3ecd43df02.png)

**Comment by mohitreddy03** [comment]
![image](https://user-images.githubusercontent.com/61975605/107538898-71298d80-6bea-11eb-9417-477060386a9c.png)
![image](https://user-images.githubusercontent.com/61975605/107538918-77b80500-6bea-11eb-9f9a-ce5b47ef613a.png)
