### ISSUE TITLE
redirect user when clicking contact us to our email in the add events page

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#306]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when we cant contact the company for extra tokens

**Describe the solution you'd like**
add something to contact us like a email link

**Describe alternatives you've considered**
we could have also redirected to our website

- [x] make a company email
- [x] add that email link

**Comment by sbangariGIT** [comment]
@mohitreddy03 can you create an email for runbhumi ?

**Comment by mohitreddy03** [comment]
> @mohitreddy03 can you create an email for runbhumi ?
> 

Not a business account rite?

**Comment by sbangariGIT** [comment]
> > @mohitreddy03 can you create an email for runbhumi ?
> 
> Not a business account rite? @sbangariGIT

no, normal gmail should do

**Comment by mohitreddy03** [comment]
Runbhumi12@gmail.com
runbhumi 2020

**Comment by mohitreddy03** [comment]
Password: runbhumi2020

**Comment by hayat-tamboli** [comment]
woa
change the pass word and tell the password in whatsapp
this is an opensource platform
