### ISSUE TITLE
select team for challenge button has a bug

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#319]
**To Reproduce**
1. challenge a team
2. Click on a team
3. nothing happens and the user may click the button multiple times
4. See an error

**Expected behavior**
change the page to the team's page and show a snack bar saying your challenge request is sent

**Screenshots**
![image](https://user-images.githubusercontent.com/55529269/107351472-a651b500-6af0-11eb-9a8b-e86f9eb0ae6a.png)
![image](https://user-images.githubusercontent.com/55529269/107351515-b8335800-6af0-11eb-987c-04cc5ce44770.png)

**Comment by Manas1820** [comment]
I am not getting this somehow can you explain more when you are getting this?
