### ISSUE TITLE
add a btn which redirects user to faq page(refer image)

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#325]
![image](https://user-images.githubusercontent.com/55529269/107356781-3b57ac80-6af7-11eb-9cbe-bc4278e63cb8.png)

**Comment by Manas1820** [comment]
![image](https://user-images.githubusercontent.com/53006261/107385479-ed53a080-6b18-11eb-8125-15bc5de2437e.png)
![image](https://user-images.githubusercontent.com/53006261/107385455-e9c01980-6b18-11eb-8da5-53f8be1d1b92.png)

Will this work ?

**Comment by Manas1820** [comment]
cool

**Comment by Manas1820** [comment]
Yes Sure

**Comment by hayat-tamboli** [comment]
> ![image](https://user-images.githubusercontent.com/53006261/107385479-ed53a080-6b18-11eb-8125-15bc5de2437e.png)
> ![image](https://user-images.githubusercontent.com/53006261/107385455-e9c01980-6b18-11eb-8da5-53f8be1d1b92.png)
> 
> Will this work ?
> 

 Ye sab PR me dalte hai bhai
Issues me questions puch sakte ho

**Comment by Manas1820** [comment]
cool
