### ISSUE TITLE
bug: user can create infinite teams and events

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#333]
https://user-images.githubusercontent.com/55529269/107772136-d0f67480-6d61-11eb-8199-5f9f23820e68.mp4

https://user-images.githubusercontent.com/55529269/107772164-deabfa00-6d61-11eb-8afc-d4c86d6ccc4e.mp4

**To Reproduce**
1. Go to 'create team/event'
2. Click on 'create team/event'
3. when pop up comes click outside the popup immediately then you can click create team/event

**Expected behavior**
when popup arrives user should not be able to close the popup 

**Screenshots**
![image](https://user-images.githubusercontent.com/55529269/107772567-66920400-6d62-11eb-8910-5422d5a82f1d.png)

**Comment by sbangariGIT** [comment]
IS it okay if i remove the success dialogue all together

**Comment by hayat-tamboli** [comment]
no dont remove the dialog ,that dialog gives the user a sense of completion of task and happiness
