### ISSUE TITLE
events info page doesnt show which teams/individuals are there in the event

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#346]
![image](https://user-images.githubusercontent.com/55529269/108736673-d3be4a00-7557-11eb-9a48-e1b4d56af441.png)

**To Reproduce**
1. Go to 'event's description/info page'
2. slide up 'teams/individuals joined'
3. See error

**Expected behavior**
there should shown a list of teams/individuals who joined

**Comment by Manas1820** [comment]
![WhatsApp Image 2021-02-23 at 1 30 41 PM](https://user-images.githubusercontent.com/53006261/108817067-5210ff80-75dd-11eb-91c4-7e89d74de8f4.jpeg)
It's showing for me
