### ISSUE TITLE
why is the CaptiansID a list

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#55]
**Describe the bug**
Captains can be only one in a group
why a list is used 

**Expected behavior**
there should be a string to each captain

**Comment by hayat-tamboli** [comment]
### its also defying abstraction concept of OOPS which is needed to make that app secure

**Comment by sbangariGIT** [comment]
for chatrooms which involve 2 teams we will have two captain Ids

**Comment by mohitreddy03** [comment]
yeah for the chats between teams there will be 2 captains.

**Comment by Manas1820** [comment]
we can save it in two different strings don't leave a loophole for people! it makes our app prone to hack as an external request can easily be sent to the DB if someone knows that its a string

**Comment by mohitreddy03** [comment]
In that case they can add players to the players list too rite? and for that we don't have any option either cause the number of players in a team are not constant.
Fine i'll change it for the captains , but what should we do for the players? or teams?

**Comment by Manas1820** [comment]
I am checking a way to block that too I thought that later.

**Comment by mohitreddy03** [comment]
okay
