### ISSUE TITLE
we should not add .dart_tool

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#7]
according to [github's gitignore file for flutter](https://github.com/flutter/flutter/blob/master/.gitignore) we shoudn't add .dart_tool/ files in the remote repo. .dart_tol/ is like nodemodules **we should not add them here**

@sbangariGIT please look into this issue

**Comment by hayat-tamboli** [comment]
#### when I merged your pull request lagnuage suddenly changed from dart to makefile, which should not happen.

**Comment by sbangariGIT** [comment]
Trying to locate those files, can you explain the language change in brief

**Comment by hayat-tamboli** [comment]
> Trying to locate those files, can you explain the language change in brief

I reverted that pull request, so now you cannot see the changes. But the main lang of the repo became makefile lang rather than dart which was weird, so I researched about this and then I found out that we shouldn't add .dart_tools/

**Comment by sbangariGIT** [comment]
So the issue is solved right? Next time while I updated I shouldn't add .dart_tools/

**Comment by hayat-tamboli** [comment]
- [ ] just update the readme and write the  `code` to setup this app in development mode in our systems.

for example, to use a website based on javascript we type `npm install`  on our terminal to set it up.

as I don't know much abt flutter so I can't type the code.
