### ISSUE TITLE
make a profile Edit page

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#76]
**Describe the solution you'd like**

- [x] make the frontend end part of it connecting that from profile page drawer

- [ ] make the backend part of it in firebase to edit the profile details such as bio and profile photo and name(if possible)

**Comment by krish-bhanushali** [comment]
Can I contribute in this?

**Comment by hayat-tamboli** [comment]
sure,
@Manas1820 please provide the requirements

**Comment by krish-bhanushali** [comment]
Great I will start after that, following the wireframe!

**Comment by hayat-tamboli** [comment]
![image](https://user-images.githubusercontent.com/55529269/95680230-bf576180-0bf5-11eb-854e-02043133376d.png)

⬆️ follow this

## skip the authorisation by changing 

![image](https://user-images.githubusercontent.com/55529269/95680302-4ad0f280-0bf6-11eb-9f13-9ccffaf9607d.png)
to 
![image](https://user-images.githubusercontent.com/55529269/95680320-6e943880-0bf6-11eb-9eb8-2c52390a16c8.png)

in **lib/view/splash/splash.dart**

then go to the profile page and open side drawer, you will get a button named edit profile click it, and that's where you are going to do the work(**lib/view/drawer/editProfile.dart**)

**Comment by krish-bhanushali** [comment]
@krish-bhanushali thankyou!

**Comment by krish-bhanushali** [comment]
Hey @hayat-tamboli  can you please mention the version of Flutter you have used ?

**Comment by hayat-tamboli** [comment]
> Hey @hayat-tamboli  can you please mention the version of Flutter you have used ?
> 

1.22.0 stable

**Comment by hayat-tamboli** [comment]
### Can I know the progress @krish-bhanushali and by when will the page complete.

**Comment by krish-bhanushali** [comment]
@hayat-tamboli I have completed the UI.  Should I first do a PR with UI and later I work on backend or all together?

**Comment by hayat-tamboli** [comment]
Make a PR with the UI you made, backend will be handled by @manas1820 
**do attach screenshots of the UI in your PR**

**Comment by Manas1820** [comment]
Good Job @krish-bhanushali

**Comment by krish-bhanushali** [comment]
Thankyou @Manas1820 you can also ping me if you need any help regarding backend.
