### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sainiteshb** [Runbhumi/Runbhumi#81]
At present the app's major color seems to be white and since the UI is beautiful I think dark mode would be great , if you want you can assign me this issue.

**Comment by hayat-tamboli** [comment]
actually, we already have a dark mode but you can enhance it,
better add a switch in the profile page-> drawer to toggle it,

**Comment by sainiteshb** [comment]
adding a switch button between the modes?

**Comment by sainiteshb** [comment]
in the drawer shall i  add option to switch theme ? Just confirm so I can work on it .

**Comment by hayat-tamboli** [comment]
Yaa you can do that

**Comment by sainiteshb** [comment]
Okay
