### ISSUE TITLE
Add testing cases

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#84]
Add different testing cases in the app

**Comment by aryanve** [comment]
widget test or integration test ?

**Comment by hayat-tamboli** [comment]
##### both, more unit tests and fewer integration tests.

**Comment by aryanve** [comment]
> ##### both, more unit tests and fewer integration tests.

I will do that!

**Comment by Manas1820** [comment]
@aryanve wats the Status?
