### ISSUE TITLE
expansion tile not working in dark mode

### ISSUE THREAD

**Issue by hayat-tamboli** [Runbhumi/Runbhumi#93]
**Describe the bug**
expansion tile not working in dark mode

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'profile page'
2. Click on 'dark mode'
3. Go to 'home page'
4. Click on 'any event'
5. See an error

**Expected behavior**
when the event card is expanded the text colour should not change

**Screenshots**
![image](https://user-images.githubusercontent.com/55529269/95745119-22a6c980-0cb2-11eb-9042-88e64bccf02f.png)

**Additional context**
flutter version 1.22.0

**Comment by bibekpanda55** [comment]
I can solve this issue ca  you please assign this to me

**Comment by bibekpanda55** [comment]
I can solve this issue please assign it to me

**Comment by hayat-tamboli** [comment]
> I can solve this issue please assign it to me

@bibekpanda55 please tag the person who created the issue so that the person gets a Notification 

@march93 from next time, **please request to assign the issue to yourself then send a PR**, this behaviour is against the open-source ethics.
